# Generated by Django 5.2.4 on 2025-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_resume_achievements_resume_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github_links',
            field=models.TextField(blank=True),
        ),
    ]
