# Generated by Django 5.2.4 on 2025-09-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_resume_github_links'),
    ]

    operations = [
    ]
